package:
  name: scmethq
  version: 1.1.2
        
  source:
    path: D:\Test\scMethTools
    
  build:
    number: 0
  
  requirements:
    build:
      - python >=3
      - setuptools
    run:
      - python >=3
      - numpy >=1.20
      - scipy
      - pandas
      - scikit-learn >=0.22
      - lightgbm
      - matplotlib
      - seaborn
      - plink >=1.9
      - pybedtools
  
  test:
    source_files:
      - run_test.py
      - cropgbm/testdata/*

  about:
    home: https://wentting.github.io/scMethQ/
    license: MIT
    description: To address the specific characteristics of single-cell DNA methylation data, we developed a comprehensive downstream analysis and visualization tool, scMethQ, employing an improved methylation quantification scheme. Testing with multiple real datasets demonstrated the advantages of scMethtools, particularly in managing the high complexity and heterogeneity of single-cell DNA methylation data. This tool significantly enhances the accuracy and efficiency of single-cell DNA methylation data analysis.
    doc_url: https://wentting.github.io/scMethQ/
